//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Resources/Input Actions/InputActionsDefault.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace InputCustom
{
    public partial class @InputActionsDefault: IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @InputActionsDefault()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputActionsDefault"",
    ""maps"": [
        {
            ""name"": ""InGame"",
            ""id"": ""ca76cf3d-c6b3-4c3f-9aee-7083f718fcee"",
            ""actions"": [
                {
                    ""name"": ""SetScaleSide"",
                    ""type"": ""Value"",
                    ""id"": ""0175dacf-cc8c-496e-bf32-1958a72bab22"",
                    ""expectedControlType"": ""Integer"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""SetScaleDirection"",
                    ""type"": ""Value"",
                    ""id"": ""063ac403-86ab-425d-bbec-52c92bb5a89c"",
                    ""expectedControlType"": ""Integer"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""48f6b44d-d15d-4ded-8947-3a018d7155ab"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SetScaleDirection"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""29ba9703-30ce-4b03-afcf-a3874dbb357a"",
                    ""path"": ""<Mouse>/scroll/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SetScaleDirection"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""1735b483-0dcf-4497-9ef0-16572403603a"",
                    ""path"": ""<Mouse>/scroll/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SetScaleDirection"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""41b92893-a000-410d-91b8-14bf0bba0755"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SetScaleSide"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""c96a3af4-e39c-4fbe-bd09-4fb244c7aff9"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SetScaleSide"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""5d6ec33d-28f0-40d7-b1fc-48935191181c"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SetScaleSide"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // InGame
            m_InGame = asset.FindActionMap("InGame", throwIfNotFound: true);
            m_InGame_SetScaleSide = m_InGame.FindAction("SetScaleSide", throwIfNotFound: true);
            m_InGame_SetScaleDirection = m_InGame.FindAction("SetScaleDirection", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }

        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }

        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // InGame
        private readonly InputActionMap m_InGame;
        private List<IInGameActions> m_InGameActionsCallbackInterfaces = new List<IInGameActions>();
        private readonly InputAction m_InGame_SetScaleSide;
        private readonly InputAction m_InGame_SetScaleDirection;
        public struct InGameActions
        {
            private @InputActionsDefault m_Wrapper;
            public InGameActions(@InputActionsDefault wrapper) { m_Wrapper = wrapper; }
            public InputAction @SetScaleSide => m_Wrapper.m_InGame_SetScaleSide;
            public InputAction @SetScaleDirection => m_Wrapper.m_InGame_SetScaleDirection;
            public InputActionMap Get() { return m_Wrapper.m_InGame; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(InGameActions set) { return set.Get(); }
            public void AddCallbacks(IInGameActions instance)
            {
                if (instance == null || m_Wrapper.m_InGameActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_InGameActionsCallbackInterfaces.Add(instance);
                @SetScaleSide.started += instance.OnSetScaleSide;
                @SetScaleSide.performed += instance.OnSetScaleSide;
                @SetScaleSide.canceled += instance.OnSetScaleSide;
                @SetScaleDirection.started += instance.OnSetScaleDirection;
                @SetScaleDirection.performed += instance.OnSetScaleDirection;
                @SetScaleDirection.canceled += instance.OnSetScaleDirection;
            }

            private void UnregisterCallbacks(IInGameActions instance)
            {
                @SetScaleSide.started -= instance.OnSetScaleSide;
                @SetScaleSide.performed -= instance.OnSetScaleSide;
                @SetScaleSide.canceled -= instance.OnSetScaleSide;
                @SetScaleDirection.started -= instance.OnSetScaleDirection;
                @SetScaleDirection.performed -= instance.OnSetScaleDirection;
                @SetScaleDirection.canceled -= instance.OnSetScaleDirection;
            }

            public void RemoveCallbacks(IInGameActions instance)
            {
                if (m_Wrapper.m_InGameActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            public void SetCallbacks(IInGameActions instance)
            {
                foreach (var item in m_Wrapper.m_InGameActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_InGameActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        public InGameActions @InGame => new InGameActions(this);
        public interface IInGameActions
        {
            void OnSetScaleSide(InputAction.CallbackContext context);
            void OnSetScaleDirection(InputAction.CallbackContext context);
        }
    }
}
